language: node_js
node_js: node
cache:
  yarn: true
  directories:
    - node_modules
services:
  - mongodb
script:
  - yarn run lint
  - yarn test
deploy:
  provider: heroku
  api_key:
    secure: uPx5S392mjVlbtzi3Zfvw+tTf86S8htpxe64j7IA3vp/A1FtRNBscenrPsxD+Z2KTdYDuuOanzS1/xB0HC7Zntgz7z6n7wU5wXLMh25bsAIWezImJ1cT5PyfVwbT45umRK3I7dJPUwSfAHEEvIOXjrt1XfjgXr+W25gKxTe3Wk2g3AAyJ4KF8bMkYgTsoICLQjvpHz6K6epc3FJZM9/Ls28yo9J9Drew64q8fllW5UKKiflbNy2jn7wU4GDf54K4K65G95TxByN4fCu5C4JVx0MXdQJ3rEngPPEmTHKrU6be6Bgqlq4ssGxYbSAgvxNcNvgZJdTntjx0WVIy9qB2enyHEfwb7RQaShFqtKzA4p/IkhMWH//huirBMU+mOyU4UgQ9ys2axwUfZTxM7+OAVOkTUIz3ajl7TqX3kbOoJ2Ioz1e2GJ1EQfpRx5A2NNvmVQhcFDTtHS5Am8QbgDcsv9/wt0lopiWxLyyl0gubduqYDqubjbxn6eoqzhRLgaq9p7V8D+VY85OersGH0EA4by3OzEJ5BD/VkIYN48BjdyXyhjQ7NbqlcIULXhiM2e2ayF+gEXv/m7wam1lo8esymhgRZ172OaCkdBRR0AD+JUfTyDCNIWGOh+1Lt+EQ8bevp6mrS346NdI4+dPRPKTLsJynG7V4QBUEZLfe4C17Vsg=
  app: osd-sidekick
  on:
    repo: open-source-developers/back-end
